"@startuml Логическая структура БД для Библиотеки"

skinparam MaxMessageSize 30

left header 
<font color=red>Библиотека</font>
endheader
' Таблица  Читатели, id Номер читательского билета первичный ключ
class Читатели{
   id Номер читательского билета 
   __
   ФИО
   Адрес
   Телефон
}
note left : Сущность читатели

' В этой таблице id Карточка книги первичный ключ, 
' номер читательского билета и шифр книги  внешние ключи
class Карточка{
   id Карточка книги
   __
   id Номер читательского билета
   id Шифр книги
}
note left : Таблица для связи номера билета и шифра книги

Читатели --> Карточка : один ко многим
'  один читатель может взять много книг
Книги --> Карточка : один ко многим
' одна книга может быть в разное время у многих читателей
' либо экземпляры одной книги одновременно у многих

' Первичный ключ id Шифр книги
class Книги{
   id Шифр книги
   __
   Название
   Автор(ы)
   Год издания
   Объем (в страницах)
   Цена
   Количество в фонде
}
note left : Сущность книги


' Разве нельзя сделать издательство 
' в таблицу Книги ?
' Первичный ключ id Издательства
class Издательство{
   id Название издательства
   __
   Город(в котором находится)
}
note right : Сущность издательство
Издательство ----> Книги : один  ко многим
' одно издательство может печатать много книг
Книги -----> Издательство : один ко многим
' одна книга может быть напечатана в 
' нескольких издательствах

@enduml